### ISSUE TITLE
Get 404 error

### ISSUE THREAD

**Issue by jasonburnell98** [sophtron/tbdex-widget#2]
I updated `SophtronApiUserId` and `SophtronApiUserSecret` value on `server/config.js` file and ran the app by following `Readme` file, but the app doesn't work and I am getting 404 error.
Should I update something else?

![image](https://user-images.githubusercontent.com/50059791/190939339-be0ec916-ebcf-48f5-9fc0-d9ee519d9068.png)

**Comment by Jishun** [comment]
You haven't start the server, you'll need to start both server and client and visit port '8080' instead

**Comment by jasonburnell98** [comment]
Thanks, it works!
